### ISSUE TITLE
Latest docker image for minidlna does not seem to start

### ISSUE THREAD

**Issue by carlonluca** [vladgh/docker_base_images#104]
Hello,
I updated to latest version of minidlna and I could not start it. This is the error from the logs:

```
minidlna.c:1048: warn: Starting MiniDLNA version 1.2.1.
minidlna.c:283: fatal: ERROR: Failed to open sqlite database!  Exiting...
minidlna.c:1048: warn: Starting MiniDLNA version 1.2.1.
minidlna.c:283: fatal: ERROR: Failed to open sqlite database!  Exiting...
minidlna.c:1048: warn: Starting MiniDLNA version 1.2.1.
minidlna.c:283: fatal: ERROR: Failed to open sqlite database!  Exiting...
minidlna.c:1048: warn: Starting MiniDLNA version 1.2.1.
minidlna.c:283: fatal: ERROR: Failed to open sqlite database!  Exiting...
minidlna.c:1048: warn: Starting MiniDLNA version 1.2.1.
minidlna.c:283: fatal: ERROR: Failed to open sqlite database!  Exiting...
minidlna.c:1048: warn: Starting MiniDLNA version 1.2.1.
minidlna.c:283: fatal: ERROR: Failed to open sqlite database!  Exiting...
```

Had to downgrade to f95087fc.
Any idea why?
Regards.

**Comment by vladgh** [comment]
I just pushed a PR earlier today which allows changing the UID and GID for the minidlna user, but in theory, it shouldn't affect the configuration and the database. Can you please let me know how you are starting this container, especially what mount points are you using. Do you mount the /minidlna folder in order to preserve the settings?

**Comment by carlonluca** [comment]
Hello,
thanks for your answer. No, I'm not mounting /minidlna. Does this mean that the sqlite database is supposed to be recreated with the container?
This is my configuration:

    minidlna:
        container_name: pihome_minidlna
        image: vladgh/minidlna:f95087fc
        restart: always
        network_mode: "host"
        user: "${CURRENT_UID}:${CURRENT_GID}"
        environment:
            - MINIDLNA_MEDIA_DIR_1=...
            - MINIDLNA_MEDIA_DIR_2=...
            - MINIDLNA_MEDIA_DIR_3=...
            - MINIDLNA_FRIENDLY_NAME=...
        volumes:
            - ...
            - ...
            - ...

Maybe the user entry is the point here?
Note that I'm on arm64.
Regards.

**Comment by vladgh** [comment]
I think so too. Instead of `user: "${CURRENT_UID}:${CURRENT_GID}"` can you use the following environment variables:

```
    environment:
        - PUID=${CURRENT_UID}
        - PGID=${CURRENT_GID}
```

**Comment by carlonluca** [comment]
Tested and this seems to properly fix. Thanks.
