### ISSUE TITLE
How to set translation

### ISSUE THREAD

**Issue by escoand** [vladgh/docker_base_images#105]
In the minidlna sources are language files for different languages. But I havn't found an info how to use them. Can you add some doc how to do so? Thanks in advance.

**Comment by vladgh** [comment]
I am not very familiar with the subject, but as far as I see, Locales support on Alpine is still under development for musl libc. You might need this to install different locales in the docker image to allow applications to support multilingual.
Did you find an answer since posting this issue?

**Comment by escoand** [comment]
No, not yet. Tried different env vars `LANG`, `LC_*`, ... without success. If this is not implemented in musl this would explain why...
