### ISSUE TITLE
[minidlna] Ошибка работы со всеми сборками, после 0.5.0

### ISSUE THREAD

**Issue by vsimanin** [vladgh/docker_base_images#129]
Добрый день!
В мае установил minidlna вашей сборки (Спасибо). Все чудесно работало по текущий день. Решил пересобрать в докере сборку на latest, выявил, что не стартует ниодна из тех, что вышла после декабря 2020 года.
![err](https://user-images.githubusercontent.com/9263449/127507600-45501fb0-e10d-4960-be47-a6a40d03263e.PNG)
Установку делал по мануалу: host, TZ=Europe/Moscow. Видно, что такая таймзона есть на моем raspberryPi

Откатился на vladgh/minidlna:0.5.0, ошибка ушла.
Буду рад, если поможете.

**Comment by vladgh** [comment]
On start, the container installs tzdata and sets up the timezone. I think the problem here is internet connectivity. I see a "temporary error (try again later)" which means that the packages were not downloaded, so the zoneinfo is missing. Make sure that the container has access to internet.

However, thanks for bringing this up, because I think I should change this in a future release, and not rely on internet for the container to start.

**Comment by vsimanin** [comment]
Ошибка никуда не ушла. Все работает на версии 0.5.0, но начиная с последующих версий dlna не стартует:

usermod: no changes,
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.14/main: temporary error (try again later),
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.14/community: temporary error (try again later),
cp: can't stat '/usr/share/zoneinfo/UTC': No such file or directory,
minidlna.c:1124: warn: Starting MiniDLNA version 1.3.0.,
minidlna.c:395: warn: Creating new database at /minidlna/cache/files.db,
minidlna.c:1193: warn: HTTP listening on port 8200,
playlist.c:135: warn: Parsing playlists...,
playlist.c:269: warn: Finished parsing playlists.,
monitor.c:222: warn: WARNING: Inotify max_user_watches [8192] is low or close to the number of used watches [4] and I do not have permission to increase this limit.  Please do so manually by writing a higher value into /proc/sys/fs/inotify/max_user_watches.,
usermod: no changes,
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.14/main: temporary error (try again later),
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.14/community: temporary error (try again later),
cp: can't stat '/usr/share/zoneinfo/UTC': No such file or directory,
minidlna.c:1124: warn: Starting MiniDLNA version 1.3.0.,
minidlna.c:1193: warn: HTTP listening on port 8200,
monitor.c:222: warn: WARNING: Inotify max_user_watches [8192] is low or close to the number of used watches [4] and I do not have permission to increase this limit.  Please do so manually by writing a higher value into /proc/sys/fs/inotify/max_user_watches.,
usermod: no changes,
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.14/main: temporary error (try again later),
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.14/community: temporary error (try again later),
cp: can't stat '/usr/share/zoneinfo/UTC': No such file or directory,
minidlna.c:1124: warn: Starting MiniDLNA version 1.3.0.,
minidlna.c:1193: warn: HTTP listening on port 8200,
monitor.c:222: warn: WARNING: Inotify max_user_watches [8192] is low or close to the number of used watches [4] and I do not have permission to increase this limit.  Please do so manually by writing a higher value into /proc/sys/fs/inotify/max_user_watches.,
usermod: no changes,
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.14/main: temporary error (try again later),
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.14/community: temporary error (try again later),
cp: can't stat '/usr/share/zoneinfo/UTC': No such file or directory,
minidlna.c:1124: warn: Starting MiniDLNA version 1.3.0.,
minidlna.c:1193: warn: HTTP listening on port 8200,
monitor.c:222: warn: WARNING: Inotify max_user_watches [8192] is low or close to the number of used watches [4] and I do not have permission to increase this limit.  Please do so manually by writing a higher value into /proc/sys/fs/inotify/max_user_watches.,
usermod: no changes,
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.14/main: temporary error (try again later),
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.14/community: temporary error (try again later),
cp: can't stat '/usr/share/zoneinfo/UTC': No such file or directory,
minidlna.c:1124: warn: Starting MiniDLNA version 1.3.0.,
minidlna.c:1193: warn: HTTP listening on port 8200,
monitor.c:222: warn: WARNING: Inotify max_user_watches [8192] is low or close to the number of used watches [4] and I do not have permission to increase this limit.  Please do so manually by writing a higher value into /proc/sys/fs/inotify/max_user_watches.,
usermod: no changes,
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.14/main: temporary error (try again later),
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.14/community: temporary error (try again later),
cp: can't stat '/usr/share/zoneinfo/UTC': No such file or directory,
minidlna.c:1124: warn: Starting MiniDLNA version 1.3.0.,
minidlna.c:1193: warn: HTTP listening on port 8200,
monitor.c:222: warn: WARNING: Inotify max_user_watches [8192] is low or close to the number of used watches [4] and I do not have permission to increase this limit.  Please do so manually by writing a higher value into /proc/sys/fs/inotify/max_user_watches.,

**Comment by vladgh** [comment]
Does the container have access to the internet? And are you still using the TZ environment variable? If you do, then it requires the internet.

**Comment by vsimanin** [comment]
> 
> 
> Does the container have access to the internet? And are you still using the TZ environment variable? If you do, then it requires the internet.

I do not restrict Internet access to the content (Network = host)
The only thing I change is the build parameter. With 0.5.0 the image is started, and with the latest - no.

**Comment by vsimanin** [comment]
I collected again, explicitly indicating TZ:
![1](https://user-images.githubusercontent.com/9263449/131912957-da523f84-bd94-40e3-b523-8b22fa0c78fa.PNG)
![2](https://user-images.githubusercontent.com/9263449/131912970-7cf2aa4d-cbf3-4a99-b15d-67f12d2e5bad.PNG)
![3](https://user-images.githubusercontent.com/9263449/131912975-ee04cda7-06ba-4797-8c12-262126b43dc0.PNG)

**Comment by vladgh** [comment]
Can you ping the servers?

```
ping dl-cdn.alpinelinux.org
```

**Comment by vsimanin** [comment]
> ping dl-cdn.alpinelinux.org

![изображение](https://user-images.githubusercontent.com/9263449/131914759-88511172-ef6e-4296-8d4f-2c06adb775fb.png)

**Comment by vladgh** [comment]
So I see!

In Alpine setting manually the timezone is obsolete (https://wiki.alpinelinux.org/wiki/Setting_the_timezone) and the recommended way is to use the setup-timezone script (https://wiki.alpinelinux.org/wiki/Alpine_setup_scripts#setup-timezone) 

I think this is the culprit, and it does not update the repository cache.

I will look into a way to override this or manually install it.

**Comment by vladgh** [comment]
I gave tested and retested this in every scenario I could imagine, but I was unable to recreate your issue. The script works as intended, and it changes the timezone without a problem. I can only suggest you cleanup/prune your images and make sure you have the latest one.
I also don't understand why you have that PATH environment variable, because that is already declared. I don't see very clearly but maybe there is a typo there, in the formatting.

**Comment by vsimanin** [comment]
> 
> 
> I gave tested and retested this in every scenario I could imagine, but I was unable to recreate your issue. The script works as intended, and it changes the timezone without a problem. I can only suggest you cleanup/prune your images and make sure you have the latest one. I also don't understand why you have that PATH environment variable, because that is already declared. I don't see very clearly but maybe there is a typo there, in the formatting.





The latest version doesn't throw a timezone error, but it doesn't work for me. 

`     

=== Set user and group identifier


usermod: no changes


=== Set standard configuration


=== Set configuration from environment variables


=== Set permissions


=== Generate scan/rebuild flags


=== Start daemon


minidlna.c:1124: warn: Starting MiniDLNA version 1.3.0.


minidlna.c:395: warn: Creating new database at /minidlna/cache/files.db


scanner.c:731: warn: Scanning /mnt


minidlna.c:1193: warn: HTTP listening on port 8200


scanner.c:820: warn: Scanning /mnt finished (0 files)!


playlist.c:135: warn: Parsing playlists...


playlist.c:269: warn: Finished parsing playlists.


monitor.c:222: warn: WARNING: Inotify max_user_watches [8192] is low or close to the number of used watches [7] and I do not have permission to increase this limit.  Please do so manually by writing a higher value into /proc/sys/fs/inotify/max_user_watches.


=== Set user and group identifier


usermod: no changes


=== Set standard configuration


=== Set configuration from environment variables


=== Set permissions


=== Generate scan/rebuild flags


=== Start daemon


minidlna.c:1124: warn: Starting MiniDLNA version 1.3.0.


minidlna.c:1193: warn: HTTP listening on port 8200


monitor.c:222: warn: WARNING: Inotify max_user_watches [8192] is low or close to the number of used watches [7] and I do not have permission to increase this limit.  Please do so manually by writing a higher value into /proc/sys/fs/inotify/max_user_watches.


upnphttp.c:1250: error: send(res_buf): Connection reset by peer


upnphttp.c:1250: error: send(res_buf): Connection reset by peer


=== Set user and group identifier


usermod: no changes


=== Set standard configuration


=== Set configuration from environment variables


=== Set permissions


=== Generate scan/rebuild flags


=== Start daemon


minidlna.c:1124: warn: Starting MiniDLNA version 1.3.0.


minidlna.c:1193: warn: HTTP listening on port 8200


monitor.c:222: warn: WARNING: Inotify max_user_watches [8192] is low or close to the number of used watches [7] and I do not have permission to increase this limit.  Please do so manually by writing a higher value into /proc/sys/fs/inotify/max_user_watches.


upnphttp.c:1250: error: send(res_buf): Connection reset by peer


upnphttp.c:1250: error: send(res_buf): Connection reset by peer

      `

**Comment by vsimanin** [comment]
> This issue has been marked 'stale' due to lack of recent activity. If there is no further activity, the issue will be closed in another 30 days. Thank you for your contribution!

Problem is actual!
