### ISSUE TITLE
[minidlna] MiniDLNA not showing me any playlists

### ISSUE THREAD

**Issue by spiral6** [vladgh/docker_base_images#134]
By running the following command,

`docker cp minidlna:/minidlna/cache/files.db /home/spiral6/minidlna.db`

And then proceeding to copy over that database file to my local PC, I can open it up with a SQLite browser.

However, this is where the problem arises. I can see that the Playlists have been correctly determined and detected by the MiniDLNA server: 
![image](https://user-images.githubusercontent.com/2887489/130319877-46ef5361-6d30-45b1-9a53-bb93a73614f9.png)

But I cannot find them in the actual MiniDLNA server themselves. There is a file `testplaylist.m3u` inside of my /media/music/Playlists/ folder. But the MiniDLNA server cannot list it.

![image](https://user-images.githubusercontent.com/2887489/130320158-701fc824-89c9-48c6-8235-cfcc4bd59c98.png)

**Comment by vladgh** [comment]
Double-check that the database has the right permissions inside the running container:

```
docker exec -it minidlna bash
```

and then look inside the `/minidlna` and `/minidlna/cache` folders. They should be owed by the `minidlna` user.

![Screenshot 2021-08-22 095530](https://user-images.githubusercontent.com/370069/130359796-f515091a-2280-4a3d-87b7-71397debf7a2.png)

**Comment by spiral6** [comment]
![image](https://user-images.githubusercontent.com/2887489/130470877-61187015-7861-41f3-97b4-bfaf016f91a5.png)

I believe it's working as expected.

**Comment by spiral6** [comment]
I'm still having this issue at this time.

**Comment by vladgh** [comment]
Did you manage to figure this out? I am not familiar enough with how playlists work in minidlna to give any advice.

**Comment by spiral6** [comment]
Nope, I have found no solution to this issue.

**Comment by ssb22** [comment]
I recently ran into a similar "MiniDLNA not showing M3U playlists" issue (although not in Docker in my case), and I solved it by checking the MiniDLNA source code for how it actually handles M3U playlists.

The `.m3u` format is able to take URL lines starting `https://`, `http://` or `file://` with URL-encoded filenames (using `%` hex codes).  VLC for example generates this kind of `.m3u` file, along with extended-format comments.  But **MiniDLNA does *not* support this type of m3u file.**  The C code in MiniDLNA recognises only *paths to files* in the m3u file (*not* `file://` URLs with `%` hex codes), and ignores all extended-format comments.  And if it gets an `m3u` file it doesn't understand, it ignores that `m3u` file.

Therefore, to make MiniDLNA recognise an `m3u` playlist, you have to use a command like `find /full/path/to/music -type f | sort > list.m3u` and *not* generate the m3u file via VLC or similar (which generates `%`-encoded `file://` URIs that MiniDLNA's C code does not recognise as valid).
