### ISSUE TITLE
Adding inotify to entrypoint.sh

### ISSUE THREAD

**Issue by nezach1** [vladgh/docker_base_images#140]
Hi there,
would it be sensible to add
`echo "inotify=yes" >>/etc/minidlna.conf`
to entrypoint.sh on line 40?
I see that file updates in the shared folders will be than updated directly into the minidlna database.

Thanks for your work. I am loving you implementation. Works like a charm.
_I am new to github, so not sure how everything works around here._

**Comment by vladgh** [comment]
I made a few changes to the settings generation and I added what you suggested.
