### ISSUE TITLE
MiniDLNA root_container

### ISSUE THREAD

**Issue by erasor2010** [vladgh/docker_base_images#167]
Hey, is it possible to define the root_container as a environment variable? Tried it it in TrueNAS Scale so its start in the Browse Directory Folder on My TV but its not working

**Comment by vladgh** [comment]
You should be able to set any configuration option by just capitalizing it and prefixing it with `MINIDLNA_`. To set `root_container` in the system-wide configuration file, the environment variable would be `MINIDLNA_ROOT_CONTAINER`.
