### ISSUE TITLE
Backup restore doesn't work

### ISSUE THREAD

**Issue by danimbrogno** [vladgh/docker_base_images#17]
Hey, I'm using your backup image and it works great but I'm having an issue restoring.

When I call the restore command I get the error:

`fatal error: Parameter validation failed:
Invalid bucket name "s3:": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$"`

If I echo out the bucket name it's trying to use I get:

`s3://s3://[my-bucket]/[prefix]/[prefix]/hourly/2017-06-28_03-00-04.tar.xz`

so it seem the s3:// gets doubled and the [prefix] gets doubled as well in the url construction.

Changing linke 167 in entrypoint.sh from

`aws s3 cp "s3://${AWS_S3_PATH}/${RESTORE_FILE}" "$RESTORE_FILE"`

to

`aws s3 cp "s3://${AWS_S3_BUCKET}/${RESTORE_FILE}" "$RESTORE_FILE"`

Seems to fix the path.

**Comment by danimbrogno** [comment]
One other issue, if you choose not to encrypt your backup, the backup works fine but the restore fails because it attempts to decrypt a tar that is not encrypted. I fixed this by changing lines 172-177

```
 export RESTORE_FILE_DECRYPTED="decrypted.tar.xz"
  if [[ -s "$RESTORE_FILE" ]]; then
    log "Decrypt ${RESTORE_FILE}"
    export GPG_TTY=/dev/console
    gpg --batch --output "$RESTORE_FILE_DECRYPTED" --decrypt "$RESTORE_FILE"
  fi
```

to

```
export RESTORE_FILE_DECRYPTED=$RESTORE_FILE
  if [[ -n "$GPG_RECIPIENT" ]] && [[ -s "$RESTORE_FILE" ]]; then
    export RESTORE_FILE_DECRYPTED="decrypted.tar.xz"
    log "Decrypt ${RESTORE_FILE}"
    export GPG_TTY=/dev/console
    gpg --batch --output "$RESTORE_FILE_DECRYPTED" --decrypt "$RESTORE_FILE"
  fi
```

I'm not super familiar with bash scripting and haven't tested whether an encrypted backup restore works with this modified code.

I can submit a PR if so desired.

**Comment by vladgh** [comment]
Thanks for reporting this. I will fix it by the end of this week.

**Comment by vladgh** [comment]
Hi @danimbrogno, I have fixed the restore function and also did  a major refactor of the code in the entrypoint, so that it's cleaner and easier to debug. https://github.com/vladgh/docker_base_images/commit/c87169993daf05b042983e51e886d51ee04f3bab should take care if this. Check the examples I added in the README. Some more testing would be appreciated, let me know if it works okay or not.
