### ISSUE TITLE
Healthcheck don't pass when minidlna tcp port is changed.

### ISSUE THREAD

**Issue by Hadatko** [vladgh/docker_base_images#246]
Hello, thank you for this container i am trying today.
I am getting this warning/error. Are we able to solve it somehow?

I don't know if this is the rootcouse of the unhealty state of container but until this message there wasn't unhealty state:

![image](https://github.com/vladgh/docker_base_images/assets/13130700/8fa2c741-d6bf-4a9f-b16d-8bb7bf46996b)

**Comment by vladgh** [comment]
Please share the log output from the container.

**Comment by Hadatko** [comment]
Actually i tried reboot container and it is unhealty also without the warning above:
<img width="219" alt="image" src="https://github.com/vladgh/docker_base_images/assets/13130700/456d00cf-a2d4-420f-9df9-7233a0c5314c">

And failure count is increasing

**Comment by Hadatko** [comment]
I see that you are running healtcheck on different port than it is defined in minidlna enviroment variable.
`curl --silent --fail 127.0.0.1:8200 || exit 1`

IS this the reason for it?

**Comment by vladgh** [comment]
Yes, that must be it. But that's not something I can modify at build time, in the image. You must override the health check at runtime, in Portainer or docker-compose, or whatever you use.

**Comment by Hadatko** [comment]
You cannot set Healtcheck to something like this?
```sh
HEALTHCHECK --interval=10s --timeout=10s --retries=6 CMD \
  sh -c 'test -n "$MINIDLNA_PORT" || MINIDLNA_PORT=8200; \
  curl --silent --fail "http://127.0.0.1:$MINIDLNA_PORT" || exit 1'
  ```

**Comment by Hadatko** [comment]
I see this in image:
<img width="583" alt="image" src="https://github.com/vladgh/docker_base_images/assets/13130700/ae37c74b-25e8-4c9f-bd85-aef1ff2ccc7b">
But this in container using newer image:
<img width="322" alt="image" src="https://github.com/vladgh/docker_base_images/assets/13130700/f5d16503-1628-4efb-a6bb-c0bb1b756433">

I will try changes locally and see

**Comment by vladgh** [comment]
It should work as expected:

![Screenshot 2023-08-09 at 9 46 19 AM](https://github.com/vladgh/docker_base_images/assets/370069/22a93b4a-9465-4b6c-a8ee-d5a7838313db)
![Screenshot 2023-08-09 at 9 46 45 AM](https://github.com/vladgh/docker_base_images/assets/370069/57fe7a18-9c4d-4432-a372-9b92693c3e01)
![Screenshot 2023-08-09 at 9 46 30 AM](https://github.com/vladgh/docker_base_images/assets/370069/6af37851-b148-4056-8249-68854773c8da)

**Comment by Hadatko** [comment]
Hi finally it is working. Not sure where was the issue, but minidlna is now using correct Healthcheck updated command (maybe i had to recreate minidlna, or do update on stack context and not container context...)
