### ISSUE TITLE
s3Sync container can't exclude certain files/directories.

### ISSUE THREAD

**Issue by giriparus** [vladgh/docker_base_images#291]
In our use case, we wanted to sync a directory that also had a log file. This would trigger a sync every time the log was updated and also backup the log file. This inflated the AWS bills.

**Comment by giriparus** [comment]
I have made some changes to make this work. Here's the [PR](https://github.com/vladgh/docker_base_images/pull/292).

**Comment by vladgh** [comment]
Thank you! PR #292 is now merged.
