### ISSUE TITLE
Failed to set TZ, due to tzdata missing from image

### ISSUE THREAD

**Issue by dittodhole** [vladgh/docker_base_images#296]
Hi, and thanks for this sleek docker image ❤️ 

When setting env `TZ` to eg `Europe/Vienna` the container fails to start, as the timezone is missing.
I've also tried to utilize `command: bash -c "apk add tzdata"`, but this fails in `minidlna.c:830`.

Any chance to add `tzdata` to https://github.com/vladgh/docker_base_images/blob/main/minidlna/Dockerfile#L7?

Best
Andreas

**Comment by vladgh** [comment]
HI Andreas, I cannot replicate this. Seems to work fine. Alpine has it's own tzdata scripts, called by this image at the beginning, and as long as the time zone is a string that exists in the [database](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), it should work.
May I ask how are you defining the env?

**Comment by vladgh** [comment]
That exact compose file gives me:

```sh
=== Set user and group identifier
=== Set timezone
=== Set standard configuration
=== Set configuration from environment variables
=== Set permissions
=== Generate scan/rebuild flags
=== Start daemon
minidlna.c:1134: warn: Starting MiniDLNA version 1.3.3.
minidlna.c:394: warn: Creating new database at /minidlna/cache/files.db
minidlna.c:1182: warn: HTTP listening on port 8200
playlist.c:135: warn: Parsing playlists...
playlist.c:269: warn: Finished parsing playlists.
```

The only thing I can think of is to do a `docker pull vladgh/minidlna:latest` maybe you have a really old version of my image, before it had time zone support.

**Comment by vladgh** [comment]
And they said Docker will eliminate the "It works on my computer" problem 😡

I will look into it some more, but for now, I'm not sure what to tell you.

**Comment by vladgh** [comment]
Remove the image completely, all versions, and pull it again. Maybe try to run it somewhere else, a different VM or machine.
