### ISSUE TITLE
Prefix gets doubled when restoring a backup so archive not copied

### ISSUE THREAD

**Issue by danimbrogno** [vladgh/docker_base_images#30]
When restoring a backup using a prefix this function causes the prefix to get doubled so the aws s3 cp command fails.

```
get_archive(){
  if [[ -s $_restore_file ]]; then
    return
  else
    # Download the latest archive from S3
    set_up_s3
    _restore_file="$(get_latest_s3_archive)"

    if [[ -n "$_restore_file" ]]; then
      aws s3 cp "${_aws_s3_path}/${_restore_file}" "$_restore_file"
    fi
  fi
}
```

With a prefix of "myprefix" the script attempts to copy the backup from: "myprefix/myprefix/hourly..."

The issue is that `aws_s3_path` has the prefix at the end, and `restore_file` has the prefix at the start.

**Comment by vladgh** [comment]
Thanks for reporting this @danimbrogno 

I will take care of it.

**Comment by vladgh** [comment]
Let me know if this take care if the issue.
At this point you should be able to specify `AWS_S3_BUCKET` and `AWS_S3_PREFIX`, and you'll end up with a path like `s3://bucket/prefix/hourly/file.tar.xz.gpg`

**Comment by danimbrogno** [comment]
That fixed it, it works beautifully now. Thanks for this super useful container!
