### ISSUE TITLE
Codecs issue

### ISSUE THREAD

**Issue by kriloleg** [vladgh/docker_base_images#58]
Hi @vladgh.

Your dockerized minidlna really great! Thank you for it.

Is it possible to add support for more formats for dlna server? Like example, avi is not exposed by server to clients. Maybe in scope of this, if some additional codecs are missing too it could be added to image.

Thanks

**Comment by vladgh** [comment]
Hi @kriloleg

I am not very familiar with the DLNA protocol, but I was under the impressions that the supported formats are dependent on the player you use (TV, Roku, etc). Some DLNA servers, like Plex, will transcode the video on the fly into a recognizable format, supported by your device, but I don't think minidlna does that, though. I might be wrong. If you find some documentation/examples on this I will gladly add it to the docker image. Meanwhile, I will do some research into the subject as well.

Thanks.

**Comment by kriloleg** [comment]
Hi, @vladgh.

Yep, I also thought this way. One thing here I can add that some AVI opens fine. 

If you will find anything about exposing more formats it would be cool, but it's not so important. AVI is not widely used and support depends on video/audio packed inside.

**Comment by shakkhar** [comment]
What media types you can play depends on your minidlna renderer. My Samsung smart TV, for example, supports mkv, avi, mp4 and aac - among other formats.

**Comment by cwoac** [comment]
stock minidnla* does not support transcoding. There does exist a version with transcoding that is used in (for example) arch linux [here](https://bitbucket.org/stativ/readymedia-transcode), but I don't believe it is in alpine so it would be a fair chunk of work to add to this.

*technically now called readymedia, but that's an aside.
