### ISSUE TITLE
Multiple "media_dir" configuration not supported in MiniDLNA container

### ISSUE THREAD

**Issue by sgoryachkin** [vladgh/docker_base_images#63]
Multiple "media_dir" configuration not supported in MiniDLNA container. In this case only last variable applied to minidlna config file.

```
-e MINIDLNA_media_dir=V,/media/Movies \
-e MINIDLNA_media_dir=PV,/media/Photos \
```

**Comment by vladgh** [comment]
This should be fixed now. Check the README for reference.

**Comment by sgoryachkin** [comment]
Thank you!
