### ISSUE TITLE
[s3sync] Issue with sync_files and $dst when uploading to s3

### ISSUE THREAD

**Issue by chiefy** [vladgh/docker_base_images#68]
Getting `can't mkdir s3://` when trying to sync from local -> s3. I think the logic needs to be changed to check if `${dst}` is s3 or local before trying to `mkdir`? I'll try to submit a PR

**Comment by vladgh** [comment]
Thanks @chiefy for bringing this up. It should be fixed now.

**Comment by chiefy** [comment]
👍 wow thanks for the quick fix!
