### ISSUE TITLE
Using with windows

### ISSUE THREAD

**Issue by inShu** [vladgh/docker_base_images#79]
Hi,
I'm trying to use this image on windows 10. Running with host network mode but still dlna server can't be discovered by any device (only by windows dlna client, in other words: by local service).
Also I can't reach web ui right through 192.165.1.3:8200. 192.165.1.3 is the host machine where docker container with minidlna was installed. But I can reach it through docker nat: 10.0.7.51:8200 from windows machine of course.
Do you have any thoughts why is that so ?

Thank you

**Comment by vladgh** [comment]
How do you run this container (compose or run directly)? Do you mind sharing it?

**Comment by inShu** [comment]
Hi,

With docker-compose:
> version: '3'
> services:
>   dlna:
>     image: "vladgh/minidlna"
>     restart: unless-stopped
>     environment:
>       - MINIDLNA_MEDIA_DIR=/media
>       - MINIDLNA_FRIENDLY_NAME=Finished
>     volumes:
>       - E:\torrents\tmp\downloads:/media
>     network_mode: "host"
> 
> networks:
>   proxy:
>     driver: bridge

**Comment by vladgh** [comment]
I see you are missing the port configuration - https://docs.docker.com/compose/compose-file/#ports

For this you need to open port 8200.

**Comment by inShu** [comment]
Port forwarding is not applied in case you using 'host' type of network. It's just ignored. In case I will add:
```
    ports:
      - "8200:8200"

```
To docker-compose and will start with docker-compose up -d. Then I will end up with:
PS G:\> docker ps -a
```
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                  PORTS                                                                    NAMES
040b857a3b5b        vladgh/minidlna        "/sbin/tini -- /entr…"   2 minutes ago       Up 2 minutes                                                                                     just_dlna_1

```
But in case I will comment out #network_mode: "host" line:

> PS G:\> docker ps -a
> CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                        PORTS                                                                    NAMES
> 9a2754000edb        vladgh/minidlna        "/sbin/tini -- /entr…"   5 seconds ago       Up 4 seconds                  0.0.0.0:8200->8200/tcp

**Comment by vladgh** [comment]
Leave out `network_mode: host` and try the following:

```yaml
ports:
  - target: 8200
    published: 8200
    protocol: tcp
    mode: host
```

**Comment by inShu** [comment]
Oh my god, I just found - https://docs.docker.com/network/network-tutorial-host/
Quoting:

> The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server.
Is this relevant?

**Comment by inShu** [comment]
Also:

> Per-container IP addressing is not possible
> The docker (Linux) bridge network is not reachable from the Windows host. However, it works with Windows containers.

Have you ever managed to run your container under windows?

**Comment by vladgh** [comment]
I will close this for now, unless there is anything new.

**Comment by emoxam** [comment]
well we can publish 8200 ? will it work ?
