### ISSUE TITLE
[minidlna] bridge mode / host mode

### ISSUE THREAD

**Issue by LennyLip** [vladgh/docker_base_images#89]
Can't make work network dlna server discovering with bridge mode.

Also (need to add UPD port to readme?), https://help.ubuntu.com/community/MiniDLNA :

```
OPEN_TCP="8200"
OPEN_UDP="1900"
```

It seems, issue related to different networks 172.17.0.0 (container) and 192.1.0.0 (local).  Can you please add to the readme working bridge mode configuration?

ps. host mode works fine.

**Comment by vladgh** [comment]
You need to run the container in host mode for it to be able to receive UPnP broadcast packets. Bridge mode will not work because it separates the container and local network.

**Comment by LennyLip** [comment]
So, we need to add --net=host to [Readme](https://github.com/vladgh/docker_base_images/blob/master/minidlna/README.md)?

**Comment by LennyLip** [comment]
UP. So, we need to remove -p parameter from the readme ?

https://docs.docker.com/network/host/

> Note: Given that the container does not have its own IP-address when using host mode networking, port-mapping does not take effect, and the -p, --publish, -P, and --publish-all option are ignored

**Comment by vladgh** [comment]
That sounds like a good idea. I'll update the README and also add a note about the host mode.
Thanks.

**Comment by NelsonVides** [comment]
I have a question here: **why** does it not work?

**Comment by LennyLip** [comment]
> I have a question here: **why** does it not work?

https://github.com/moby/libnetwork/issues/2397#issuecomment-935029813
