### ISSUE TITLE
Arm64 images

### ISSUE THREAD

**Issue by ttopalov** [vladgh/docker_base_images#91]
I am using this image:
https://hub.docker.com/r/vladgh/minidlna
on arm64 by copying the dockerfile and building it manually. It works great, but it would be even easier if multi-platform build was enabled in docker hub and images for armhf and arm64 were available there.
Great work btw!

**Comment by vladgh** [comment]
Thank you! I am currently looking into the multiarch build of this, and there is also a PR open (https://github.com/vladgh/docker_base_images/pull/90) However, see my comment (https://github.com/vladgh/docker_base_images/pull/90#pullrequestreview-332761985)

**Comment by ttopalov** [comment]
Thanks for the quick response! I absolutely agree with your response in #90 and can confirm the minidlna dockerfile built and executed successfully on arm64 without modifications.

**Comment by vladgh** [comment]
https://github.com/vladgh/docker_base_images/pull/90#issuecomment-572781721

**Comment by ttopalov** [comment]
I can confirm the new dlna image works on arm64.
