### ISSUE TITLE
MiniDLNA. ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

### ISSUE THREAD

**Issue by svonidze** [vladgh/docker_base_images#92]
Getting the error while trying to run the container on mini computers: odroid-xu4 and raspberry pi 3 model b+.

**Comment by vladgh** [comment]
I added support for 32bit distros (arm/v6, arm/v7). For now only for the `latest` image. Let me know if it works. 
When docker hub will support buildx I will update my build scripts.

**Comment by svonidze** [comment]
It works, ty!

PS. Could you clarify what you have done to fix that? My guess from your comment: 
- you utilized https://github.com/docker/buildx for building versions for many platforms/architectures (linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64)
- then just pushed all images to hub.docker.com manually?

PPS before the fix I used the repository https://github.com/fmartingr/docker-minidlna-arm where as the architecture was hardcoded `FROM armhf/alpine:latest`

**Comment by vladgh** [comment]
You are correct. Below is the script I use to manually update the latest image for different platforms. I use this because it transparently downloads the right architecture. Another method would be to tag each architecture separately.

```sh
export DOCKER_CLI_EXPERIMENTAL=enabled
docker buildx create --name mybuilder --use
docker buildx build --rm --pull --push --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8 -t vladgh/minidlna .
docker buildx rm mybuilder
```
